name: Deploy ProudIT Solutions

on:
  push:
    branches:
      - master

jobs:
  deploy: 
    runs-on: self-hosted

    steps:
      - name: Pulling new code
        run: |
          sudo -u actionsrunner bash -c "
          cd /home/Proud_IT_Solutions/website_pn
          git pull origin master
          "

      - name: Install packages
        run: |
          sudo -u actionsrunner bash -c "
          cd /home/Proud_IT_Solutions/website_pn
          echo 'Installing npm packages...'
          npm ci
          "

      - name: Building Project
        run: |
          sudo -u actionsrunner bash -c "
          cd /home/Proud_IT_Solutions/website_pn
          echo 'Building project...'
          npm run build
          "

      - name: Restarting Application using PM2
        run: |
          sudo -u actionsrunner bash -c "
          cd /home/Proud_IT_Solutions/website_pn
          echo 'Restarting PM2 process...'
          pm2 restart pn || pm2 start npm --name 'pn' -- start
          pm2 save
          "

      - name: Showing PM2 Status
        run: |
          sudo -u actionsrunner bash -c "pm2 status"
