name: Deploy ProudIT Solutions

on:
  push:
    branches:
      - master

jobs:
  deploy: 
    runs-on: self-hosted

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Testing Runner Connection
        run: echo "Testing Runner Connection by Devops Engineer Sanjeev Adhikari"

  