name: Deploy ProudIT Solutions

on:
  push:
    branches:
      - master

jobs:
  deploy: 
    runs-on: self-hosted

    steps:
      - name: Pulling new code
        run: |
          cd /home/Proud_IT_Solutions/website_pn
          git pull origin master

      - name: Install packages
        run: |
          echo "npm installing"
          cd /home/Proud_IT_Solutions/website_pn
          npm install


      - name: Building Project
        run: |
          echo "building project"
          cd /home/Proud_IT_Solutions/website_pn
          npm run build

      - name: Restarting Application using PM2
        run: sudo -u actionsrunner bash -c "export HOME=/home/actionsrunner && pm2 restart pn || pm2 start npm --name pn -- start"

      - name: Showing PM2 Status
        run: pm2 status
  